#!/usr/bin/env python3
"""
Fetch the most recent Strava run or Hevy workout, whichever is newer,
and write it to src/data/activity.ts.

Required GitHub secrets:
  STRAVA_CLIENT_ID      — from https://www.strava.com/settings/api
  STRAVA_CLIENT_SECRET
  STRAVA_REFRESH_TOKEN  — obtained from the one-time auth flow (see README)
  HEVY_API_KEY          — from Hevy app → Profile → API
"""

import json
import os
import sys
from datetime import datetime, timezone

import requests


# ── Strava ────────────────────────────────────────────────────────────────────

def strava_access_token() -> str:
    r = requests.post(
        "https://www.strava.com/oauth/token",
        data={
            "client_id": os.environ["STRAVA_CLIENT_ID"],
            "client_secret": os.environ["STRAVA_CLIENT_SECRET"],
            "refresh_token": os.environ["STRAVA_REFRESH_TOKEN"],
            "grant_type": "refresh_token",
        },
        timeout=10,
    )
    r.raise_for_status()
    return r.json()["access_token"]


def fetch_strava() -> dict | None:
    try:
        token = strava_access_token()
    except Exception as e:
        print(f"Strava token refresh failed: {e}", file=sys.stderr)
        return None

    try:
        r = requests.get(
            "https://www.strava.com/api/v3/athlete/activities",
            params={"per_page": 1},
            headers={"Authorization": f"Bearer {token}"},
            timeout=10,
        )
        r.raise_for_status()
        acts = r.json()
    except Exception as e:
        print(f"Strava activities fetch failed: {e}", file=sys.stderr)
        return None

    if not acts:
        return None

    a = acts[0]
    mi = a.get("distance", 0) / 1609.34
    t = a.get("moving_time", 0)
    h, m, s = t // 3600, (t % 3600) // 60, t % 60
    finish = f"{h}:{m:02d}:{s:02d}" if h else f"{m}:{s:02d}"
    pace = f"{int(t / mi // 60)}:{int(t / mi % 60):02d}" if mi else "—"

    dt = datetime.fromisoformat(a["start_date_local"].replace("Z", "+00:00"))
    epoch = dt.replace(tzinfo=timezone.utc).timestamp()

    return {
        "type": "run",
        "label": f"last {a.get('type', 'Run').lower()}",
        "name": a.get("name", "Activity"),
        "date": dt.strftime("%b %-d"),
        "finish": finish,
        "pace": pace,
        "distance": f"{mi:.1f} mi",
        "href": f"https://www.strava.com/activities/{a['id']}",
        "_epoch": epoch,
    }


# ── Hevy ──────────────────────────────────────────────────────────────────────

def fetch_hevy() -> dict | None:
    key = os.environ.get("HEVY_API_KEY", "")
    if not key:
        return None

    try:
        r = requests.get(
            "https://api.hevyapp.com/v1/workouts",
            params={"page": 1, "pageSize": 1},
            headers={"api-key": key},
            timeout=10,
        )
        r.raise_for_status()
        workouts = r.json().get("workouts", [])
    except Exception as e:
        print(f"Hevy fetch failed: {e}", file=sys.stderr)
        return None

    if not workouts:
        return None

    w = workouts[0]
    exs = w.get("exercises", [])
    secs = w.get("duration", 0)
    start_raw = w.get("start_time", "")

    try:
        dt = datetime.fromisoformat(start_raw.replace("Z", "+00:00"))
        epoch = dt.timestamp()
        date_str = dt.strftime("%b %-d")
    except ValueError:
        epoch = 0
        date_str = ""

    return {
        "type": "workout",
        "label": "last lifted",
        "name": w.get("title", "Workout"),
        "date": date_str,
        "duration": f"{secs // 60} min",
        "sets": str(sum(len(e.get("sets", [])) for e in exs)),
        "exercises": str(len(exs)),
        "_epoch": epoch,
    }


# ── Write TypeScript ──────────────────────────────────────────────────────────

TS_TEMPLATE = """\
// Auto-generated by .github/workflows/update-activity.yml
// Last updated: {ts}

export interface RunActivity {{
  type: "run";
  label: string;
  name: string;
  date: string;
  finish: string;
  pace: string;
  distance: string;
  href: string;
}}

export interface WorkoutActivity {{
  type: "workout";
  label: string;
  name: string;
  date: string;
  duration: string;
  sets: string;
  exercises: string;
}}

export type Activity = RunActivity | WorkoutActivity;

// Most recent activity — whichever of Strava/Hevy happened last.
export const latestActivity: Activity | null = {data};
"""


def write_ts(activity: dict | None) -> None:
    if activity is not None:
        clean = {k: v for k, v in activity.items() if not k.startswith("_")}
        data = json.dumps(clean, indent=2)
    else:
        data = "null"

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    content = TS_TEMPLATE.format(ts=ts, data=data)

    out = os.path.join(os.path.dirname(__file__), "..", "src", "data", "activity.ts")
    with open(out, "w") as f:
        f.write(content)

    print(f"✓ activity.ts updated ({activity['type'] if activity else 'null'}) at {ts}")


# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    run = fetch_strava()
    workout = fetch_hevy()

    candidates = [x for x in [run, workout] if x is not None]
    latest = max(candidates, key=lambda x: x["_epoch"]) if candidates else None

    write_ts(latest)
