// Auto-generated by .github/workflows/update-activity.yml
// Last updated: 2026-04-13 10:03 UTC

export interface RunActivity {
  type: "run";
  label: string;
  name: string;
  date: string;
  finish: string;
  pace: string;
  distance: string;
  href: string;
}

export interface WorkoutActivity {
  type: "workout";
  label: string;
  name: string;
  date: string;
  duration: string;
  sets: string;
  exercises: string;
}

export type Activity = RunActivity | WorkoutActivity;

// Most recent activity — whichever of Strava/Hevy happened last.
export const latestActivity: Activity | null = null;
