// Auto-generated by .github/workflows/update-activity.yml
// Seed with manual data; the workflow overwrites this daily.

export interface RunActivity {
  type: "run";
  label: string;
  name: string;
  date: string;
  finish: string;
  pace: string;
  distance: string;
  href: string;
}

export interface WorkoutActivity {
  type: "workout";
  label: string;
  name: string;
  date: string;
  duration: string;
  sets: string;
  exercises: string;
}

export type Activity = RunActivity | WorkoutActivity;

// Most recent activity — whichever of Strava/Hevy happened last.
export const latestActivity: Activity | null = {
  type: "run",
  label: "last run",
  name: "Saucony Love Run Philly",
  date: "Mar 29",
  finish: "1:57:49",
  pace: "8:59",
  distance: "13.1 mi",
  href: "https://results.laurelt.com/luv/results?pk=8716661",
};
